function fullContextVector = genFullContextVector(enc)
values = enc.params.BACParams;

fullContextVector = [values.contextVector4DTIndependent...
     values.contextVector2DTIndependent...
     values.contextVector4DTMasked...
     values.contextVector2DTMasked...
     values.contextVector4DTORImages...
     values.contextVector3DTORImages...
     values.contextVector2DTORImages...
     values.contextVector4DT...
     values.contextVector3DT...
     values.contextVector2DT...
];


fullContextVector = logical(fullContextVector);
