% Author: Eduardo Peixoto
% E-mail: eduardopeixoto@ieee.org
function cabac = getHTables()

cabac = struct('BACParams',[],...
               'BACContexts_2D_Masked',[],...
               'BACContexts_3D_ORImages',[],...
               'BACContexts_2DT_Independent',[],...
               'BACContexts_2DT_Masked',[],...
               'BACContexts_3DT_ORImages',[],...
               'BACContexts_3DT',[],...
               'BACContexts_3D',[]);