% Author: Eduardo Peixoto
% E-mail: eduardopeixoto@ieee.org
function bac_params = getBACParams()

bac_params = struct('m',16,...
                    'maxValueContext',4096,...
                    'numberOfContextsIndependent',8,...
                    'numberOfContextsMasked',6,...
                    'windowSizeFor3DContexts',1,...
                    'numberOf3DContexts',10,...
                    'windowSizeFor4DContexts',0,...
                    'numberOf4DContexts',0,...  
                    'numberOfContexts3DOnly',5,...
                    'numberOfContextsParams',4);
                   