% Author: Eduardo Peixoto
% E-mail: eduardopeixoto@ieee.org
function ptCloud = getPointCloudStruct()

ptCloud = struct('Location',[],...
                 'Count',0,...
                 'XLimits',[0 0],...
                 'YLimits',[0 0],...
                 'ZLimits',[0 0]);
                   